
CREATE TABLE `User` (
		id bigint generated by default as identity,
		email varchar(255), password varchar(255),
		primary key (id)
		);
		
-- Inserting some example data
INSERT INTO `User` (email, password) VALUES ('user1', 'password123');
INSERT INTO `User` (email, password) VALUES ('user2@example.com', 'securepass');